//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KonyvtarKliens.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Konyv", Namespace="http://schemas.datacontract.org/2004/07/KonyvtarService")]
    [System.SerializableAttribute()]
    public partial class Konyv : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringFormatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string k_CimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int k_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string k_MufajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int k_OldalszamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringFormatum {
            get {
                return this.StringFormatumField;
            }
            set {
                if ((object.ReferenceEquals(this.StringFormatumField, value) != true)) {
                    this.StringFormatumField = value;
                    this.RaisePropertyChanged("StringFormatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string k_Cim {
            get {
                return this.k_CimField;
            }
            set {
                if ((object.ReferenceEquals(this.k_CimField, value) != true)) {
                    this.k_CimField = value;
                    this.RaisePropertyChanged("k_Cim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int k_Id {
            get {
                return this.k_IdField;
            }
            set {
                if ((this.k_IdField.Equals(value) != true)) {
                    this.k_IdField = value;
                    this.RaisePropertyChanged("k_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string k_Mufaj {
            get {
                return this.k_MufajField;
            }
            set {
                if ((object.ReferenceEquals(this.k_MufajField, value) != true)) {
                    this.k_MufajField = value;
                    this.RaisePropertyChanged("k_Mufaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int k_Oldalszam {
            get {
                return this.k_OldalszamField;
            }
            set {
                if ((this.k_OldalszamField.Equals(value) != true)) {
                    this.k_OldalszamField = value;
                    this.RaisePropertyChanged("k_Oldalszam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/KonyvtarService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FnevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int JogkorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int u_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fnev {
            get {
                return this.FnevField;
            }
            set {
                if ((object.ReferenceEquals(this.FnevField, value) != true)) {
                    this.FnevField = value;
                    this.RaisePropertyChanged("Fnev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Jogkor {
            get {
                return this.JogkorField;
            }
            set {
                if ((this.JogkorField.Equals(value) != true)) {
                    this.JogkorField = value;
                    this.RaisePropertyChanged("Jogkor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Passw {
            get {
                return this.PasswField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswField, value) != true)) {
                    this.PasswField = value;
                    this.RaisePropertyChanged("Passw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int u_Id {
            get {
                return this.u_IdField;
            }
            set {
                if ((this.u_IdField.Equals(value) != true)) {
                    this.u_IdField = value;
                    this.RaisePropertyChanged("u_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KolcsonzottKonyv", Namespace="http://schemas.datacontract.org/2004/07/KonyvtarService")]
    [System.SerializableAttribute()]
    public partial class KolcsonzottKonyv : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KolcsonzoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KolcsonzottFormatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MufajField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OldalszamField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cim {
            get {
                return this.CimField;
            }
            set {
                if ((object.ReferenceEquals(this.CimField, value) != true)) {
                    this.CimField = value;
                    this.RaisePropertyChanged("Cim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kolcsonzo {
            get {
                return this.KolcsonzoField;
            }
            set {
                if ((object.ReferenceEquals(this.KolcsonzoField, value) != true)) {
                    this.KolcsonzoField = value;
                    this.RaisePropertyChanged("Kolcsonzo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KolcsonzottFormatum {
            get {
                return this.KolcsonzottFormatumField;
            }
            set {
                if ((object.ReferenceEquals(this.KolcsonzottFormatumField, value) != true)) {
                    this.KolcsonzottFormatumField = value;
                    this.RaisePropertyChanged("KolcsonzottFormatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mufaj {
            get {
                return this.MufajField;
            }
            set {
                if ((object.ReferenceEquals(this.MufajField, value) != true)) {
                    this.MufajField = value;
                    this.RaisePropertyChanged("Mufaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Oldalszam {
            get {
                return this.OldalszamField;
            }
            set {
                if ((this.OldalszamField.Equals(value) != true)) {
                    this.OldalszamField = value;
                    this.RaisePropertyChanged("Oldalszam");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListKonyvek", ReplyAction="http://tempuri.org/IService1/ListKonyvekResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/ListKonyvekExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        KonyvtarKliens.SR.Konyv[] ListKonyvek(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListKonyvek", ReplyAction="http://tempuri.org/IService1/ListKonyvekResponse")]
        System.Threading.Tasks.Task<KonyvtarKliens.SR.Konyv[]> ListKonyvekAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/RegisterExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void Register(string fnev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Register", ReplyAction="http://tempuri.org/IService1/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(string fnev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/LoginExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        KonyvtarKliens.SR.User Login(string fnev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<KonyvtarKliens.SR.User> LoginAsync(string fnev, string jelszo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertKonyv", ReplyAction="http://tempuri.org/IService1/InsertKonyvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/InsertKonyvExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void InsertKonyv(KonyvtarKliens.SR.Konyv konyv, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertKonyv", ReplyAction="http://tempuri.org/IService1/InsertKonyvResponse")]
        System.Threading.Tasks.Task InsertKonyvAsync(KonyvtarKliens.SR.Konyv konyv, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateKonyv", ReplyAction="http://tempuri.org/IService1/UpdateKonyvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/UpdateKonyvExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void UpdateKonyv(KonyvtarKliens.SR.Konyv konyv, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateKonyv", ReplyAction="http://tempuri.org/IService1/UpdateKonyvResponse")]
        System.Threading.Tasks.Task UpdateKonyvAsync(KonyvtarKliens.SR.Konyv konyv, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKonyv", ReplyAction="http://tempuri.org/IService1/DeleteKonyvResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/DeleteKonyvExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void DeleteKonyv(KonyvtarKliens.SR.Konyv konyv, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteKonyv", ReplyAction="http://tempuri.org/IService1/DeleteKonyvResponse")]
        System.Threading.Tasks.Task DeleteKonyvAsync(KonyvtarKliens.SR.Konyv konyv, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsers", ReplyAction="http://tempuri.org/IService1/getUsersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/getUsersExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        KonyvtarKliens.SR.User[] getUsers(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getUsers", ReplyAction="http://tempuri.org/IService1/getUsersResponse")]
        System.Threading.Tasks.Task<KonyvtarKliens.SR.User[]> getUsersAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Logout", ReplyAction="http://tempuri.org/IService1/LogoutResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/LogoutExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void Logout(KonyvtarKliens.SR.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Logout", ReplyAction="http://tempuri.org/IService1/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(KonyvtarKliens.SR.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Kolcsonoz", ReplyAction="http://tempuri.org/IService1/KolcsonozResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/KolcsonozExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void Kolcsonoz(KonyvtarKliens.SR.Konyv konyv, KonyvtarKliens.SR.User user, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Kolcsonoz", ReplyAction="http://tempuri.org/IService1/KolcsonozResponse")]
        System.Threading.Tasks.Task KolcsonozAsync(KonyvtarKliens.SR.Konyv konyv, KonyvtarKliens.SR.User user, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Visszavisz", ReplyAction="http://tempuri.org/IService1/VisszaviszResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/VisszaviszExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        void Visszavisz(KonyvtarKliens.SR.KolcsonzottKonyv kolcsonzott, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Visszavisz", ReplyAction="http://tempuri.org/IService1/VisszaviszResponse")]
        System.Threading.Tasks.Task VisszaviszAsync(KonyvtarKliens.SR.KolcsonzottKonyv kolcsonzott, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/kolcsonzott", ReplyAction="http://tempuri.org/IService1/kolcsonzottResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/kolcsonzottExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        KonyvtarKliens.SR.KolcsonzottKonyv[] kolcsonzott(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/kolcsonzott", ReplyAction="http://tempuri.org/IService1/kolcsonzottResponse")]
        System.Threading.Tasks.Task<KonyvtarKliens.SR.KolcsonzottKonyv[]> kolcsonzottAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listToUser", ReplyAction="http://tempuri.org/IService1/listToUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/listToUserExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        KonyvtarKliens.SR.KolcsonzottKonyv[] listToUser(KonyvtarKliens.SR.User user, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listToUser", ReplyAction="http://tempuri.org/IService1/listToUserResponse")]
        System.Threading.Tasks.Task<KonyvtarKliens.SR.KolcsonzottKonyv[]> listToUserAsync(KonyvtarKliens.SR.User user, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoggedIn", ReplyAction="http://tempuri.org/IService1/LoggedInResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/LoggedInExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        bool LoggedIn(string fnev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoggedIn", ReplyAction="http://tempuri.org/IService1/LoggedInResponse")]
        System.Threading.Tasks.Task<bool> LoggedInAsync(string fnev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckRegister", ReplyAction="http://tempuri.org/IService1/CheckRegisterResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="http://tempuri.org/IService1/CheckRegisterExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        int CheckRegister(string fnev);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckRegister", ReplyAction="http://tempuri.org/IService1/CheckRegisterResponse")]
        System.Threading.Tasks.Task<int> CheckRegisterAsync(string fnev);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : KonyvtarKliens.SR.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<KonyvtarKliens.SR.IService1>, KonyvtarKliens.SR.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KonyvtarKliens.SR.Konyv[] ListKonyvek(string username) {
            return base.Channel.ListKonyvek(username);
        }
        
        public System.Threading.Tasks.Task<KonyvtarKliens.SR.Konyv[]> ListKonyvekAsync(string username) {
            return base.Channel.ListKonyvekAsync(username);
        }
        
        public void Register(string fnev, string jelszo) {
            base.Channel.Register(fnev, jelszo);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(string fnev, string jelszo) {
            return base.Channel.RegisterAsync(fnev, jelszo);
        }
        
        public KonyvtarKliens.SR.User Login(string fnev, string jelszo) {
            return base.Channel.Login(fnev, jelszo);
        }
        
        public System.Threading.Tasks.Task<KonyvtarKliens.SR.User> LoginAsync(string fnev, string jelszo) {
            return base.Channel.LoginAsync(fnev, jelszo);
        }
        
        public void InsertKonyv(KonyvtarKliens.SR.Konyv konyv, string username) {
            base.Channel.InsertKonyv(konyv, username);
        }
        
        public System.Threading.Tasks.Task InsertKonyvAsync(KonyvtarKliens.SR.Konyv konyv, string username) {
            return base.Channel.InsertKonyvAsync(konyv, username);
        }
        
        public void UpdateKonyv(KonyvtarKliens.SR.Konyv konyv, string username) {
            base.Channel.UpdateKonyv(konyv, username);
        }
        
        public System.Threading.Tasks.Task UpdateKonyvAsync(KonyvtarKliens.SR.Konyv konyv, string username) {
            return base.Channel.UpdateKonyvAsync(konyv, username);
        }
        
        public void DeleteKonyv(KonyvtarKliens.SR.Konyv konyv, string username) {
            base.Channel.DeleteKonyv(konyv, username);
        }
        
        public System.Threading.Tasks.Task DeleteKonyvAsync(KonyvtarKliens.SR.Konyv konyv, string username) {
            return base.Channel.DeleteKonyvAsync(konyv, username);
        }
        
        public KonyvtarKliens.SR.User[] getUsers(string username) {
            return base.Channel.getUsers(username);
        }
        
        public System.Threading.Tasks.Task<KonyvtarKliens.SR.User[]> getUsersAsync(string username) {
            return base.Channel.getUsersAsync(username);
        }
        
        public void Logout(KonyvtarKliens.SR.User user) {
            base.Channel.Logout(user);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(KonyvtarKliens.SR.User user) {
            return base.Channel.LogoutAsync(user);
        }
        
        public void Kolcsonoz(KonyvtarKliens.SR.Konyv konyv, KonyvtarKliens.SR.User user, string username) {
            base.Channel.Kolcsonoz(konyv, user, username);
        }
        
        public System.Threading.Tasks.Task KolcsonozAsync(KonyvtarKliens.SR.Konyv konyv, KonyvtarKliens.SR.User user, string username) {
            return base.Channel.KolcsonozAsync(konyv, user, username);
        }
        
        public void Visszavisz(KonyvtarKliens.SR.KolcsonzottKonyv kolcsonzott, string username) {
            base.Channel.Visszavisz(kolcsonzott, username);
        }
        
        public System.Threading.Tasks.Task VisszaviszAsync(KonyvtarKliens.SR.KolcsonzottKonyv kolcsonzott, string username) {
            return base.Channel.VisszaviszAsync(kolcsonzott, username);
        }
        
        public KonyvtarKliens.SR.KolcsonzottKonyv[] kolcsonzott(string username) {
            return base.Channel.kolcsonzott(username);
        }
        
        public System.Threading.Tasks.Task<KonyvtarKliens.SR.KolcsonzottKonyv[]> kolcsonzottAsync(string username) {
            return base.Channel.kolcsonzottAsync(username);
        }
        
        public KonyvtarKliens.SR.KolcsonzottKonyv[] listToUser(KonyvtarKliens.SR.User user, string username) {
            return base.Channel.listToUser(user, username);
        }
        
        public System.Threading.Tasks.Task<KonyvtarKliens.SR.KolcsonzottKonyv[]> listToUserAsync(KonyvtarKliens.SR.User user, string username) {
            return base.Channel.listToUserAsync(user, username);
        }
        
        public bool LoggedIn(string fnev) {
            return base.Channel.LoggedIn(fnev);
        }
        
        public System.Threading.Tasks.Task<bool> LoggedInAsync(string fnev) {
            return base.Channel.LoggedInAsync(fnev);
        }
        
        public int CheckRegister(string fnev) {
            return base.Channel.CheckRegister(fnev);
        }
        
        public System.Threading.Tasks.Task<int> CheckRegisterAsync(string fnev) {
            return base.Channel.CheckRegisterAsync(fnev);
        }
    }
}
